import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Layout
    'loading': 'جاري تحميل تجربتك...',
    'dashboard': 'لوحة التحكم',
    'courses': 'الدورات',
    'plan': 'الخطة',
    'settings': 'الإعدادات',
    'admin': 'مركز التحكم',
    'signOut': 'تسجيل الخروج',
    'signIn': 'تسجيل الدخول',
    'openMenu': 'فتح القائمة',
    'close': 'إغلاق',
    'optional': 'اختياري',
    
    // Auth
    'welcomeBack': 'مرحباً بعودتك',
    'createAccount': 'إنشاء حساب',
    'signInDescription': 'أدخل بياناتك للوصول إلى حسابك',
    'signUpDescription': 'أدخل بياناتك لإنشاء حساب جديد',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirmPassword': 'تأكيد كلمة المرور',
    'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
    'passwordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'signingIn': 'جاري تسجيل الدخول...',
    'signingUp': 'جاري إنشاء الحساب...',
    'sending': 'جاري الإرسال...',
    'updating': 'جاري التحديث...',
    'signUp': 'إنشاء حساب',
    'alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'dontHaveAccount': 'ليس لديك حساب؟',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'resetPassword': 'إعادة تعيين كلمة المرور',
    'resetPasswordDescription': 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة التعيين',
    'sendResetLink': 'إرسال رابط الإعادة',
    'resetLinkSent': 'تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني',
    'setNewPassword': 'تعيين كلمة مرور جديدة',
    'newPassword': 'كلمة المرور الجديدة',
    'updatePassword': 'تحديث كلمة المرور',
    'passwordUpdated': 'تم تحديث كلمة المرور بنجاح',
    'backToSignIn': 'العودة لتسجيل الدخول',
    'checkEmail': 'تحقق من بريدك الإلكتروني للتأكيد!',
    'studySmarter': 'ادرس بذكاء',
    'notHarder': 'وليس بجهد أكبر',
    'authTagline': 'خطط ذكية مدعومة بالذكاء الاصطناعي لنجاحك الأكاديمي',
    'orContinueWith': 'أو تابع بواسطة',
    'continueWithGoogle': 'المتابعة مع Google',
    'fullName': 'الاسم الكامل',
    'fullNameRequired': 'الاسم الكامل مطلوب',
    'fullNamePlaceholder': 'أدخل اسمك الكامل',
    'completeYourProfile': 'أكمل ملفك الشخصي',
    'profileRequiredInfo': 'هذه المعلومات مطلوبة للمتابعة',
    'saveAndContinue': 'حفظ والمتابعة',
    'saving': 'جاري الحفظ...',
    'profileUpdated': 'تم تحديث الملف الشخصي',
    'verifyEmailFirst': 'يرجى التحقق من بريدك الإلكتروني أولاً',
    'checkEmailForVerification': 'تحقق من بريدك الإلكتروني وانقر على رابط التحقق للمتابعة',
    
    // Profile Fields
    'phoneNumber': 'رقم الهاتف',
    'phonePlaceholder': 'للحصول على أكواد ترويجية خاصة',
    'phoneHint': 'أضف رقم هاتفك للحصول على عروض وأكواد ترويجية حصرية',
    'department': 'القسم',
    'departmentPlaceholder': 'مثال: علوم الحاسب',
    'departmentRequired': 'القسم مطلوب',
    'university': 'الجامعة',
    'universityPlaceholder': 'مثال: جامعة الملك سعود',
    'universityRequired': 'الجامعة مطلوبة',
    
    // Settings
    'manageAccount': 'إدارة حسابك وتفضيلاتك',
    'profile': 'الملف الشخصي',
    'profileInfo': 'معلومات الملف الشخصي',
    'updateDetails': 'تحديث بياناتك الشخصية',
    'displayName': 'الاسم المعروض',
    'yourName': 'اسمك',
    'emailCannotChange': 'لا يمكن تغيير البريد الإلكتروني',
    'language': 'اللغة',
    'saveChanges': 'حفظ التغييرات',
    'dangerZone': 'منطقة الخطر',
    'studyPreferences': 'تفضيلات الدراسة',
    'customizeStudyPlan': 'تخصيص إعدادات خطة الدراسة',
    'dailyStudyHours': 'ساعات الدراسة اليومية',
    'hoursLabel': 'ساعات',
    'daysLabel': 'أيام',
    'howManyHours': 'كم ساعة يمكنك الدراسة يومياً؟',
    'studyDaysPerWeek': 'أيام الدراسة في الأسبوع',
    'savePreferences': 'حفظ التفضيلات',
    'settingsSaved': 'تم حفظ الإعدادات',
    'preferencesUpdated': 'تم تحديث تفضيلاتك',
    'saveFailed': 'فشل في الحفظ',
    'error': 'خطأ',
    'portalError': 'تعذر فتح إدارة الاشتراك. حاول مرة أخرى.',
    'welcomeToPro': 'مرحباً بك في Pro! 🎉',
    'subscriptionActive': 'اشتراكك نشط الآن. استمتع بجميع الميزات المميزة!',
    'checkoutCancelled': 'تم إلغاء عملية الدفع',
    'upgradeAnytime': 'يمكنك الترقية في أي وقت من الإعدادات.',
    
    // Subscription & Pricing
    'subscription': 'الاشتراك',
    'freePlan': 'مجاني',
    'proPlan': 'Pro',
    'currentPlan': 'الخطة الحالية',
    'freeDesc': 'ابدأ بالميزات الأساسية',
    'proDesc': 'أطلق العنان لقوة الجدولة بالذكاء الاصطناعي',
    'monthly': 'شهري',
    'annual': 'سنوي',
    'month': 'شهر',
    'save': 'وفّر',
    'billedAnnually': 'يُدفع سنوياً',
    'freeCourses': '2 مادة نشطة',
    'freeTopics': '10 مواضيع لكل مادة',
    'freeExtractions': '3 استخراجات AI شهرياً',
    'basicScheduling': 'جدولة أساسية',
    'unlimited': 'غير محدود',
    'coursesLabel': 'مادة',
    'topicsPerCourse': 'موضوع لكل مادة',
    'proExtractions': '50 استخراج AI شهرياً',
    'aiSmartScheduling': 'جدولة ذكية بالذكاء الاصطناعي',
    'spacedRepetition': 'مراجعات بالتكرار المتباعد',
    'dependencyTracking': 'تتبع تبعيات المواضيع',
    'prioritySupport': 'دعم ذو أولوية',
    'recommended': 'موصى به',
    'downgrade': 'تخفيض',
    'upgradeToPro': 'ترقية إلى Pro',
    'active': 'نشط',
    'billing': 'الفوترة',
    'renews': 'يُجدد في',
    'manageSubscription': 'إدارة الاشتراك',
    'checkoutStarted': 'بدأت عملية الدفع',
    'completePayment': 'أكمل الدفع في التبويب الجديد لتفعيل اشتراكك.',
    
    // Contact Upgrade
    'contactToUpgrade': 'تواصل معنا للترقية',
    'upgradeMessage': 'للترقية إلى الخطة الاحترافية، يرجى التواصل معنا على الرقم التالي:',
    'copyNumber': 'نسخ الرقم',
    'numberCopied': 'تم نسخ الرقم!',
    'copied': 'تم النسخ',
    
    // Course Detail - Files Tab
    'files': 'الملفات',
    'topics': 'المواضيع',
    'allocation': 'التوزيع',
    'uploadCourseMaterials': 'رفع مواد الدورة',
    'uploadedFiles': 'الملفات المرفوعة',
    'dropFilesHere': 'اسحب ملفات PDF هنا أو انقر للرفع',
    'maxFileSize': 'الحد الأقصى لحجم الملف',
    'uploading': 'جاري الرفع...',
    'extractingText': 'جاري استخراج النص...',
    'ready': 'جاهز',
    'failed': 'فشل',
    'pending': 'قيد الانتظار',
    'manualInputNeeded': 'يحتاج إدخال يدوي',
    'retry': 'إعادة المحاولة',
    'extractTopics': 'استخراج المواضيع',
    'textExtracted': 'تم استخراج النص!',
    'readyToExtract': 'جاهز لاستخراج المواضيع من',
    'extractionFailed': 'فشل استخراج النص',
    'addManually': 'يمكنك إضافة المواضيع يدوياً',
    'extractionNotice': 'ملاحظة الاستخراج',
    'fileUploaded': 'تم رفع الملف',
    
    // Course Detail - Topics Tab
    'addContent': 'إضافة محتوى',
    'pasteForAI': 'الصق المنهج أو قائمة المواضيع هنا للاستخراج بالذكاء الاصطناعي',
    'pasteSyllabusHere': 'الصق نص المنهج هنا...',
    'extractWithAI': 'استخراج المواضيع بالذكاء الاصطناعي',
    'extractingWithAI': 'جاري الاستخراج بالذكاء الاصطناعي...',
    'progressOverview': 'نظرة عامة على التقدم',
    'trackCompletion': 'تتبع إكمال المواضيع',
    'topicsCompleted': 'مواضيع مكتملة',
    'notStarted': 'لم يبدأ',
    'inProgress': 'قيد الدراسة',
    'done': 'مكتمل',
    'needsReview': 'موضوع يحتاج مراجعتك (ثقة منخفضة)',
    'topicsCount': 'المواضيع',
    'reviewTopics': 'راجع وعدّل المواضيع. حدد الأوزان (1-5) للصعوبة وأهمية الامتحان.',
    'addManualTopic': 'إضافة يدوي',
    'status': 'الحالة',
    'title': 'العنوان',
    'confidence': 'الثقة',
    'source': 'المصدر',
    'difficulty': 'الصعوبة',
    'importance': 'الأهمية',
    'score': 'الدرجة',
    'actions': 'الإجراءات',
    'high': 'عالية',
    'medium': 'متوسطة',
    'low': 'منخفضة',
    'page': 'ص',
    'noSourceContext': 'لا يوجد سياق مصدر',
    'noTopicsYet': 'لا توجد مواضيع بعد. الصق نص المنهج أعلاه أو أضف يدوياً.',
    'topicLimitReached': 'تم الوصول للحد الأقصى من المواضيع',
    'enterTextToExtract': 'الرجاء إدخال نص لاستخراج المواضيع منه',
    'loginToExtract': 'الرجاء تسجيل الدخول لاستخراج المواضيع',
    'topicsExtracted': 'تم استخراج المواضيع بنجاح!',
    'someNeedReview': 'بعض المواضيع قد تحتاج مراجعتك. تحقق من العناوين والأوزان.',
    'extractFailed': 'فشل في استخراج المواضيع',
    'deleteFailed': 'فشل في حذف الموضوع',
    'topicDeleted': 'تم حذف الموضوع',
    'updateFailed': 'فشل في تحديث الموضوع',
    'statusUpdateFailed': 'فشل في تحديث الحالة',
    
    // Course Detail - Allocation Tab
    'studySchedule': 'جدول الدراسة',
    'generateScheduleDesc': 'أنشئ خطة دراسة متوازنة من الآن حتى يوم امتحانك في',
    'basicSchedule': 'جدول أساسي',
    'aiSmartSchedule': 'جدول ذكي بالـ AI',
    'addTopicsFirst': 'أضف مواضيع لمادتك أولاً.',
    'setExamDate': 'حدد تاريخ الامتحان لإنشاء خطة.',
    'yourPlan': 'خطتك',
    'topicsScheduled': 'مواضيع مجدولة',
    'scheduleGenerated': 'تم إنشاء خطة الدراسة!',
    'noTopicsFound': 'لم يتم العثور على مواضيع. أضف مواضيع أولاً.',
    'setExamDateFirst': 'حدد تاريخ الامتحان أولاً.',
    'planError': 'خطأ في إنشاء الخطة',
    'smartPlanCreated': 'تم إنشاء الخطة الذكية',
    'daysStudySessions': 'أيام، جلسات دراسية!',
    'scheduleWarnings': 'تم إنشاء الجدول مع تحذيرات',
    'topicsCoverage': 'تم جدولة المواضيع',
    'aiCreditsExhausted': 'نفدت رصيد AI. يرجى إضافة المزيد.',
    'rateLimitExceeded': 'تم تجاوز الحد. حاول لاحقاً.',
    'smartPlanFailed': 'فشل في إنشاء الخطة الذكية',
    'planNotCreated': 'لم يتم إنشاء الخطة لأنه لم يتم إنشاء جدول صالح.',
    'extractionInProgress': 'استخراج المواضيع قيد التنفيذ بالفعل',
    'coursesExcluded': 'تم استبعاد بعض المواد - لا توجد أيام متاحة قبل الامتحان',
    'confirmDeletePlan': 'هل أنت متأكد من حذف خطة الدراسة؟ لا يمكن التراجع عن هذا.',
    'planDeleted': 'تم حذف خطة الدراسة بنجاح',
    'deletePlan': 'حذف الخطة',
    'deletePlanFailed': 'فشل في حذف الخطة',
    'priorityPlanCreated': 'تم إنشاء خطة الأولويات',
    'priorityTopicsScheduled': 'مواضيع ذات أولوية عالية مجدولة',
    'priorityModeActive': 'وضع الأولويات نشط',
    'priorityModeDesc': 'الوقت غير كافٍ لجميع المواضيع. تم جدولة المواضيع ذات الأولوية العالية. راجع علامة المواضيع للمواضيع المتبقية.',
    'viewRemainingTopics': 'عرض المواضيع المتبقية في علامة المواضيع',
    'fallbackSchedulerUsed': 'تم استخدام جدولة احتياطية',
    
    // Tips
    'filesTip': 'ارفع ملفات المنهج (PDF) لاستخراج المواضيع تلقائياً',
    'topicsTip': 'أضف المواضيع يدوياً أو استخرجها من الملفات المرفوعة',
    'allocationTip': 'شاهد كيف توزع المواضيع على الأيام المتبقية حتى الامتحان',
    
    // Exam
    'exam': 'امتحان',
    'daysLeft': 'يوم',
    'examPassed': 'انتهى الامتحان',
    
    // Landing - Navbar
    'login': 'تسجيل الدخول',
    'startFree': 'ابدأ مجاناً',
    
    // Landing - Hero
    'heroBadge': 'منصة ذكية للتفوق الدراسي',
    'heroTitle1': 'نظّم مذاكرتك',
    'heroTitle2': 'بذكاء وفعالية',
    'heroSubtitle': 'استخدم الذكاء الاصطناعي لتنظيم جدولك الدراسي تلقائياً، وتابع تقدمك حتى يوم الامتحان. تجربة دراسية متكاملة مصممة لنجاحك.',
    'startNowFree': 'ابدأ الآن مجاناً',
    'browseSchedule': 'تصفح الجدول العام',
    'activeStudents': 'طالب نشط',
    'successRate': 'نسبة النجاح',
    'studyHours': 'ساعة مذاكرة',
    
    // Landing - How it Works
    'howItWorks': 'كيف',
    'howItWorksHighlight': 'يعمل؟',
    'howItWorksSubtitle': 'أربع خطوات بسيطة تفصلك عن تنظيم مثالي لدراستك',
    'step1Title': 'أضف موادك',
    'step1Desc': 'أدخل المواد الدراسية مع تواريخ الامتحانات. يمكنك رفع ملف المنهج ليستخرج الذكاء الاصطناعي المواضيع تلقائياً.',
    'step2Title': 'خطة ذكية',
    'step2Desc': 'يقوم النظام بتوزيع المواضيع على الأيام المتبقية حسب الأهمية والصعوبة، لضمان تغطية كاملة للمنهج.',
    'step3Title': 'تابع تقدمك',
    'step3Desc': 'أكمل المهام اليومية وشاهد تقدمك في كل مادة. استخدم تقنية البومودورو للتركيز الأمثل.',
    'step4Title': 'حقق التفوق',
    'step4Desc': 'مع المتابعة المستمرة والتنظيم الذكي، ستكون جاهزاً للامتحان بثقة وهدوء.',
    
    // Landing - Features
    'featuresTitle': 'كل ما تحتاجه',
    'featuresTitleHighlight': 'في مكان واحد',
    'featuresSubtitle': 'أدوات متكاملة صُممت خصيصاً لمساعدتك على التفوق',
    'feature1Title': 'لوحة تحكم شاملة',
    'feature1Desc': 'تابع إنجازاتك اليومية وإحصائيات المذاكرة في مكان واحد',
    'feature2Title': 'جداول ذكية',
    'feature2Desc': 'جداول مخصصة تتناسب مع أوقاتك وموادك الدراسية',
    'feature3Title': 'مؤقت بومودورو',
    'feature3Desc': 'تقنية البومودورو المدمجة لجلسات دراسية فعالة ومركزة',
    'feature4Title': 'استخراج ذكي',
    'feature4Desc': 'الذكاء الاصطناعي يستخرج المواضيع من ملفاتك تلقائياً',
    'feature5Title': 'تتبع التقدم',
    'feature5Desc': 'رسوم بيانية توضح تقدمك في كل مادة بشكل مرئي',
    'feature6Title': 'إدارة المواد',
    'feature6Desc': 'نظم موادك وحدد الأولويات وتتبع كل مادة بدقة',
    
    // Landing - Footer
    'publicSchedule': 'الجدول العام',
    'allRightsReserved': 'جميع الحقوق محفوظة.',
    
    // Pomodoro
    'pomodoroTimer': 'مؤقت بومودورو',
    'focusTime': 'وقت التركيز',
    'shortBreak': 'استراحة قصيرة',
    'longBreak': 'استراحة طويلة',
    'start': 'ابدأ',
    'pause': 'إيقاف مؤقت',
    'reset': 'إعادة تعيين',
    'sessionsCompleted': 'الجلسات المكتملة',
    'sessionRecorded': 'تم تسجيل جلسة التركيز!',
    'stayFocused': 'ابقَ مركزًا! 💪',
    'takeBreak': 'استمتع باستراحتك ☕',
    'greatWork': 'عمل رائع! 🎉',
    
    // Dashboard
    'goodMorning': 'صباح الخير',
    'goodAfternoon': 'مساء الخير',
    'goodEvening': 'مساء الخير',
    'letsStudy': 'هيا نذاكر! 📚',
    'newCourse': 'مادة جديدة',
    'hoursToday': 'ساعات اليوم',
    'completedItems': 'مكتملة',
    'remainingItems': 'متبقية',
    'progress': 'التقدم',
    'todayPlan': 'خطة اليوم',
    'createPlan': 'إنشاء الخطة',
    'dailyProgress': 'التقدم اليومي',
    'generalStudy': 'مذاكرة عامة',
    'viewFullPlan': 'عرض الخطة الكاملة',
    'noPlanYet': 'لا توجد خطة بعد',
    'noPlanDesc': 'أنشئ خطة دراسية مخصصة بناءً على موادك وتواريخ امتحاناتك',
    'upcomingExams': 'الامتحانات القادمة',
    'ended': 'انتهى',
    'hours': 'س',
    
    // Dashboard - Welcome (New Users)
    'welcomeTitle': 'مرحباً بك في StudyBudy',
    'welcomeSubtitle': 'ابدأ رحلتك الدراسية بإضافة مادتك الأولى. سنساعدك في تنظيم وقتك وتحقيق أهدافك.',
    'howToStart': 'كيف تبدأ؟',
    'addFirstCourseStep': 'أضف مادتك الأولى',
    'addFirstCourseDesc': 'أدخل اسم المادة وتاريخ الامتحان، ويمكنك رفع ملف المنهج إن وُجد',
    'addTopicsStep': 'أضف المواضيع',
    'addTopicsDesc': 'أضف مواضيع المادة يدوياً أو دع الذكاء الاصطناعي يستخرجها من الملف',
    'getPlanStep': 'احصل على خطتك',
    'getPlanDesc': 'سنولّد لك جدولاً يومياً ذكياً يوزع المواضيع بناءً على الوقت المتبقي',
    'addFirstCourse': 'أضف مادتك الأولى',
    
    // TodayOverview
    'today': 'اليوم',
    'completed': 'مكتمل',
    'noTasksToday': 'لا توجد مهام مجدولة لليوم',
    'enjoyDay': 'استمتع بيومك! 🎉',
    
    // Subjects
    'os': 'نظم التشغيل',
    'circuits': 'الدوائر',
    'automata': 'الأتمتة',
    
    // Days
    'sunday': 'الأحد',
    'monday': 'الاثنين',
    'tuesday': 'الثلاثاء',
    'wednesday': 'الأربعاء',
    'thursday': 'الخميس',
    'friday': 'الجمعة',
    'saturday': 'السبت',
    
    // Study Tips
    'studyTips': 'نصائح للمذاكرة',
    'tipActiveRecallTitle': 'التذكر النشط',
    'tipActiveRecallDesc': 'اختبر نفسك بشكل متكرر بدلاً من إعادة القراءة فقط. حاول استرجاع المعلومات من ذاكرتك قبل مراجعة ملاحظاتك.',
    'tipPomodoroTitle': 'تقنية بومودورو',
    'tipPomodoroDesc': 'ادرس في فترات مركزة لمدة 25 دقيقة مع استراحات 5 دقائق. بعد 4 فترات، خذ استراحة أطول 15-30 دقيقة.',
    'tipPrioritizeTitle': 'أولوية المواضيع الصعبة',
    'tipPrioritizeDesc': 'تعامل مع المواضيع الصعبة عندما تكون طاقتك في أعلى مستوياتها، عادة في الصباح أو بعد استراحة.',
    'tipHydratedTitle': 'حافظ على الترطيب',
    'tipHydratedDesc': 'اشرب الماء بانتظام. الجفاف يمكن أن يضعف التركيز والوظائف الإدراكية بشكل كبير.',
    'tipSpacedRepTitle': 'التكرار المتباعد',
    'tipSpacedRepDesc': 'راجع المادة على فترات متزايدة. هذا يساعد في نقل المعلومات من الذاكرة قصيرة المدى إلى طويلة المدى.',

    // AddTopicDialog
    'enterTopicTitleFirst': 'الرجاء إدخال عنوان الموضوع أولاً',
    'topicAnalyzedWithAI': 'تم تحليل الموضوع بالذكاء الاصطناعي',
    'topicAnalysisFailed': 'فشل في تحليل الموضوع: ',
    'unknownError': 'خطأ غير معروف',
    'enterTopicTitle': 'الرجاء إدخال عنوان الموضوع',
    'topicAddedSuccess': 'تمت إضافة الموضوع بنجاح',
    'topicAddFailed': 'فشل في إضافة الموضوع: ',
    'addNewTopic': 'إضافة موضوع جديد',
    'addNewTopicDesc': 'أضف موضوعاً جديداً يدوياً. يمكنك تحديد الصعوبة والأهمية أو ترك الذكاء الاصطناعي يقترحها.',
    'topicTitleLabel': 'عنوان الموضوع *',
    'topicTitlePlaceholder': 'مثال: المعادلات التفاضلية',
    'notesOptional': 'ملاحظات (اختياري)',
    'notesPlaceholder': 'أي ملاحظات إضافية عن الموضوع...',
    'difficultyLabel': 'الصعوبة: ',
    'difficultyHelp': '1 = سهل، 5 = صعب',
    'importanceLabel': 'أهمية الامتحان: ',
    'importanceHelp': '1 = منخفضة، 5 = عالية',
    'analyzeWithAILabel': 'تحليل بالذكاء الاصطناعي لاقتراح الأوزان',
    'calculatedScore': 'الدرجة المحسوبة: ',
    'addTopicButton': 'إضافة الموضوع',
    'adding': 'جاري الإضافة...',
    'cancel': 'إلغاء',

    // Edit/Delete Course
    'editCourse': 'تعديل المادة',
    'editCourseDesc': 'تحديث تفاصيل المادة وتاريخ الامتحان',
    'examDate': 'تاريخ الامتحان',
    'selectDate': 'اختر تاريخ',
    'courseUpdated': 'تم تحديث المادة بنجاح',
    'courseNameRequired': 'اسم المادة مطلوب',
    'deleteCourse': 'حذف المادة',
    'deleteCourseConfirm': 'هل أنت متأكد من حذف',
    'deleteWarningTopics': 'سيتم حذف جميع المواضيع والبيانات المرتبطة.',
    'actionCannotBeUndone': 'لا يمكن التراجع عن هذا الإجراء.',
    'courseDeleted': 'تم حذف المادة بنجاح',

    // CreateCourseDialog
    'courseCreatedSuccess': 'تم إنشاء المادة بنجاح!',
    'addCourse': 'إضافة مادة',
    'addNewCourse': 'إضافة مادة جديدة',
    'addNewCourseDesc': 'أضف مادة أو امتحان تستعد له',
    'courseNameLabel': 'اسم المادة',
    'courseNamePlaceholder': 'مثال: الرياضيات المتقدمة',
    'examDateOptional': 'تاريخ الامتحان (اختياري)',
    'examDateHelp': 'سنستخدم هذا التاريخ لتوزيع المواضيع على الأيام المتبقية',
    'remainingLimit': 'متبقي لديك',
    'course': 'مادة',
    'courses_plural': 'مواد',
    'inCurrentPlan': 'في خطتك الحالية',
    'creating': 'جاري الإنشاء...',
    'createCourseButton': 'إنشاء المادة',

    // UpgradeCard
    'benefits_course_limit_1': 'أضف عدد غير محدود من المواد',
    'benefits_course_limit_2': 'استخراج ذكي للمواضيع من ملفاتك',
    'benefits_course_limit_3': 'تحليلات متقدمة لتقدمك',
    'benefits_ai_limit_1': 'استخراج ذكي غير محدود',
    'benefits_ai_limit_2': 'تحديد أولويات المواضيع تلقائياً',
    'benefits_ai_limit_3': 'إنشاء خطط دراسية أسرع',
    'benefits_general_1': 'مواد غير محدودة',
    'benefits_general_2': 'استخراج ذكي للمواضيع',
    'benefits_general_3': 'تحليلات وإحصائيات متقدمة',
    'title_course_limit': 'أضف المزيد من المواد',
    'title_ai_limit': 'افتح قوة الذكاء الاصطناعي',
    'title_general': 'ارتقِ بتجربتك الدراسية',
    'subtitle_course_limit': 'وصلت للحد الأقصى من المواد في خطتك الحالية. ترقَّ الآن لتنظيم كل موادك في مكان واحد.',
    'subtitle_ai_limit': 'استنفدت عمليات الاستخراج الذكي. ترقَّ للحصول على استخراج غير محدود للمواضيع.',
    'subtitle_general': 'احصل على أدوات قوية لتنظيم دراستك وتحقيق أهدافك الأكاديمية.',
    'upgradePlan': 'ترقية الخطة',
    'youAreInTrial': 'أنت في الفترة التجريبية',
    'planNamePrefix': 'خطة',
    'upgradeNow': 'ترقية الآن',
    'cancelAnytime': 'يمكنك الإلغاء في أي وقت • ضمان استرداد خلال 7 أيام',

    // SoftLimitWarning
    'limit_warning_courses': 'استخدمت {current} من {limit} مواد',
    'limit_critical_courses': 'مادة واحدة متبقية!',
    'limit_reached_courses': 'وصلت للحد الأقصى من المواد',
    'limit_warning_topics': '{current}/{limit} موضوع',
    'limit_critical_topics': 'مواضيع قليلة متبقية!',
    'limit_reached_topics': 'وصلت للحد الأقصى من المواضيع',
    'limit_warning_ai': '{current}/{limit} عملية استخراج',
    'limit_critical_ai': 'عملية واحدة متبقية!',
    'limit_reached_ai': 'استنفدت عمليات الاستخراج',
    'upgrade': 'ترقية',

    // PlanWarningBanner
    'severeTimeConstraint': 'قيود زمنية شديدة',
    'timeConstraintWarning': 'تحذير قيود زمنية',
    'youNeedHours': 'أنت بحاجة إلى {required} ساعات ولكن لديك فقط {available} ساعات متاحة.',
    'butHaveHours': '', // Included in previous string for RTL context simplicity
    'coverageRatio': 'نسبة التغطية: {percent}% من وقت الدراسة المثالي.',
    'ofIdealStudyTime': '', // Included above
    'studyHoursCompressed': ' تم ضغط ساعات الدراسة.',
    'considerSuggestions': 'ضع في اعتبارك: زيادة ساعات الدراسة اليومية، إضافة المزيد من أيام الدراسة، أو تأجيل الامتحان إذا أمكن.',

    // UsageIndicator
    'freeTrial': 'تجربة مجانية',
    'nearLimit': 'قاربت على الحد الأقصى',
    'usage': 'الاستخدام',

    // Courses List
    'noCoursesTitle': 'لا توجد مواد بعد',
    'noCoursesDesc': 'أضف مادتك الأولى للبدء في تنظيم دراستك. يمكنك رفع ملف المنهج أو إضافة المواضيع يدوياً.',
    'todayExclamation': 'اليوم!',
    'noExamDate': 'لم يُحدد تاريخ الامتحان',
    'completedTopicsCount': '{completed} من {total} موضوع مكتمل',

    // Exam Countdown Card
    'nextExam': 'التالي',
    'urgent': 'عاجل',
    'examCompleted': 'انتهى الامتحان',
    'daysShort': 'يوم',
    'hoursShort': 'س',
    'minutesShort': 'د',
    'secondsShort': 'ث',
    'topicsNeededPerDay': '~{count} مواضيع/يوم مطلوبة',
    'percentComplete': '{percent}% مكتمل',

    // Plan Page
    'studyPlan': 'خطة الدراسة',
    'customScheduleDesc': 'جدولك الدراسي اليومي المخصص',
    'planCreated': 'تم إنشاء الخطة!',
    'planCreatedDesc': 'تم إنشاء {days} يوم مع {items} موضوع دراسي',
    'planFailed': 'فشل في إنشاء الخطة',
    'tryAgain': 'حاول مرة أخرى',
    'weekReplanned': 'تم إعادة تخطيط الأسبوع!',
    'missedItemsDistributed': 'تم توزيع {count} موضوع متأخر على الأيام القادمة',
    'replanFailed': 'فشل في إعادة التخطيط',
    'recreatePlan': 'إعادة إنشاء الخطة',
    'daysUntilExam': 'أيام حتى الامتحان',
    'dailyHours': 'ساعات يومية',
    'remainingTopics': 'مواضيع متبقية',
    'restDay': 'يوم راحة',
    'enjoyRestDay': 'استمتع بيوم راحتك! 🌴',
    'noScheduledTopics': 'لا توجد مواضيع مجدولة',
    'tomorrow': 'غداً',
    'tasks': 'مهام',

    // Dashboard extras
    'studyTipsTitle': 'نصائح وتقنيات الدراسة',
    'tipsCount': '{count} نصائح',
    'detailedSchedule': 'الجدول التفصيلي ({days} يوم)',
    'moreDays': '+{count} أيام أخرى...',
    'viewAllExams': 'عرض جميع الامتحانات ({count})',

    // Calendar Integration
    'calendarSync': 'مزامنة التقويم',
    'connectGoogleCalendar': 'ربط تقويم Google',
    'disconnectCalendar': 'فصل التقويم',
    'calendarConnected': 'التقويم مربوط',
    'syncNow': 'مزامنة الآن',
    'syncing': 'جاري المزامنة...',
    'syncSuccess': 'تمت المزامنة بنجاح!',
    'autoSync': 'مزامنة تلقائية',
    'autoSyncDesc': 'مزامنة خطتك تلقائياً مع تقويم Google',
    'calendarNotConnected': 'التقويم غير مربوط',
    'connectCalendarDesc': 'اربط تقويم Google لإضافة خطة دراستك تلقائياً',
    'syncToCalendar': 'مزامنة مع التقويم',
    'eventsCreated': 'تم إنشاء {count} حدث في تقويمك',

    // Account Management
    'dangerZoneDesc': 'إجراءات لا يمكن التراجع عنها',
    'exportData': 'تصدير بياناتك',
    'exportDataDesc': 'تحميل جميع بياناتك بصيغة JSON',
    'export': 'تصدير',
    'exportSuccess': 'تم تصدير البيانات',
    'exportSuccessDesc': 'تم تحميل ملف البيانات بنجاح',
    'exportFailed': 'فشل في تصدير البيانات',
    'deleteAccount': 'حذف الحساب',
    'deleteAccountDesc': 'حذف حسابك وجميع بياناتك نهائياً',
    'delete': 'حذف',
    'confirmDeleteAccount': 'تأكيد حذف الحساب',
    'deleteAccountWarning': 'هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع بياناتك بما في ذلك المواد والمواضيع والخطط والملفات.',
    'enterPasswordToConfirm': 'أدخل كلمة المرور للتأكيد',
    'permanentlyDelete': 'حذف نهائي',
    'incorrectPassword': 'كلمة المرور غير صحيحة',
    'accountDeleted': 'تم حذف الحساب',
    'accountDeletedDesc': 'تم حذف حسابك وجميع بياناتك بنجاح',
    'deleteAccountFailed': 'فشل في حذف الحساب',

    // Legal Pages
    'termsOfService': 'شروط الخدمة',
    'privacyPolicy': 'سياسة الخصوصية',

    // Password Reset & File Management
    'resetPasswordTitle': 'إعادة تعيين كلمة المرور',
    'resetPasswordDesc': 'إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
    'passwordResetSent': 'تم إرسال رابط إعادة التعيين',
    'checkEmailForReset': 'تحقق من بريدك الإلكتروني للحصول على رابط إعادة التعيين',
    'confirmDeleteFile': 'تأكيد حذف الملف',
    'deleteFileWarning': 'هل أنت متأكد من حذف هذا الملف؟',
    'fileDeleted': 'تم حذف الملف بنجاح',
    'deleteFileFailed': 'فشل في حذف الملف',
    'topicQuotaReached': 'تم الوصول إلى حد الموضوعات',
    'upgradeForMoreTopics': 'قم بالترقية إلى Pro للحصول على موضوعات غير محدودة',
    
    // Upload race condition
    'waitForUploadsToFinish': 'يرجى الانتظار حتى انتهاء رفع جميع الملفات قبل استخراج المواضيع',
    
    // Triage mode warnings
    'triageModeActive': 'وضع الطوارئ نشط',
    'triageModeDesc': 'الوقت غير كافٍ لجميع المواضيع. تم جدولة المواضيع ذات الأولوية العالية فقط.',
    'viewAllTopics': 'عرض جميع المواضيع',
    'topicsNotScheduled': 'موضوع لم يتم جدولته',
    
    // Schedule errors
    'examDateConflict': 'تعارض تاريخ الامتحان',
    'noAvailableDays': 'لا توجد أيام متاحة قبل الامتحان',
    'checkExamDate': 'تحقق من تاريخ الامتحان وإعدادات أيام العطلة',
    
    // Admin
    'proOverride': 'Pro (تجاوز)',
    'trialActive': 'تجربة نشطة',
    'trialDaysLeft': 'يوم متبقي',

    // Onboarding hints
    'hintStep': 'الخطوة',
    'hintGetStarted': 'ابدأ هنا',
    'hintNoCoursesTitle': 'ابدأ رحلتك الدراسية',
    'hintNoCoursesDesc': 'أضف مادتك الأولى لتنظيم دراستك. انقر على الزر أعلاه لإضافة مادة.',
    'hintAddTopicsTitle': 'أضف مواضيعك',
    'hintAddTopicsDesc': 'بعد إنشاء المادة، أضف المواضيع يدوياً أو استخرجها من ملفات PDF.',
    'hintGeneratePlanTitle': 'أنشئ خطتك',
    'hintGeneratePlanDesc': 'بمجرد إضافة المواضيع، انتقل إلى صفحة "الخطة" لإنشاء جدول دراسي ذكي.',
    'hintNavigateToCoursesBtn': 'انتقل إلى المواد',
    'hintNavigateToPlanBtn': 'انتقل إلى الخطة',
    'nextStep': 'الخطوة التالية',
    'currentStep': 'الخطوة الحالية',
    'completedStep': 'مكتمل',
  },
  en: {
    // Layout
    'loading': 'Loading your experience...',
    'dashboard': 'Dashboard',
    'courses': 'Courses',
    'plan': 'Plan',
    'settings': 'Settings',
    'admin': 'Admin Center',
    'signOut': 'Sign Out',
    'signIn': 'Sign In',
    'openMenu': 'Open Menu',
    'close': 'Close',
    'optional': 'optional',
    
    // Auth
    'welcomeBack': 'Welcome back',
    'createAccount': 'Create an account',
    'signInDescription': 'Enter your credentials to access your account',
    'signUpDescription': 'Enter your details to create a new account',
    'email': 'Email',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'passwordsDoNotMatch': 'Passwords do not match',
    'passwordTooShort': 'Password must be at least 6 characters',
    'signingIn': 'Signing in...',
    'signingUp': 'Creating account...',
    'sending': 'Sending...',
    'updating': 'Updating...',
    'signUp': 'Sign Up',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccount': "Don't have an account?",
    'forgotPassword': 'Forgot password?',
    'resetPassword': 'Reset password',
    'resetPasswordDescription': "Enter your email and we'll send you a reset link",
    'sendResetLink': 'Send reset link',
    'resetLinkSent': 'Reset link sent to your email',
    'setNewPassword': 'Set a new password',
    'newPassword': 'New password',
    'updatePassword': 'Update password',
    'passwordUpdated': 'Password updated successfully',
    'backToSignIn': 'Back to sign in',
    'checkEmail': 'Check your email for confirmation!',
    'studySmarter': 'Study Smarter',
    'notHarder': 'Not Harder',
    'authTagline': 'AI-powered smart study plans for your academic success',
    'orContinueWith': 'or continue with',
    'continueWithGoogle': 'Continue with Google',
    'fullName': 'Full Name',
    'fullNameRequired': 'Full name is required',
    'fullNamePlaceholder': 'Enter your full name',
    'completeYourProfile': 'Complete Your Profile',
    'profileRequiredInfo': 'This information is required to continue',
    'saveAndContinue': 'Save & Continue',
    'saving': 'Saving...',
    'profileUpdated': 'Profile updated',
    'verifyEmailFirst': 'Please verify your email first',
    'checkEmailForVerification': 'Check your email and click the verification link to continue',
    
    // Profile Fields
    'phoneNumber': 'Phone Number',
    'phonePlaceholder': 'To get special promotion codes',
    'phoneHint': 'Add your phone number to receive exclusive offers and promo codes',
    'department': 'Department',
    'departmentPlaceholder': 'e.g., Computer Science',
    'departmentRequired': 'Department is required',
    'university': 'University',
    'universityPlaceholder': 'e.g., King Saud University',
    'universityRequired': 'University is required',
    
    // Settings
    'manageAccount': 'Manage your account and preferences',
    'profile': 'Profile',
    'profileInfo': 'Profile Information',
    'updateDetails': 'Update your personal details',
    'displayName': 'Display Name',
    'yourName': 'Your name',
    'emailCannotChange': 'Email cannot be changed',
    'language': 'Language',
    'saveChanges': 'Save Changes',
    'dangerZone': 'Danger Zone',
    'studyPreferences': 'Study Preferences',
    'customizeStudyPlan': 'Customize your study plan generation',
    'dailyStudyHours': 'Daily Study Hours',
    'hoursLabel': 'hours',
    'daysLabel': 'days',
    'howManyHours': 'How many hours can you study per day?',
    'studyDaysPerWeek': 'Study Days Per Week',
    'savePreferences': 'Save Preferences',
    'settingsSaved': 'Settings saved',
    'preferencesUpdated': 'Your preferences have been updated.',
    'saveFailed': 'Failed to save',
    'error': 'Error',
    'portalError': 'Could not open subscription management. Please try again.',
    'welcomeToPro': 'Welcome to Pro! 🎉',
    'subscriptionActive': 'Your subscription is now active. Enjoy all premium features!',
    'checkoutCancelled': 'Checkout cancelled',
    'upgradeAnytime': 'You can upgrade anytime from settings.',
    
    // Subscription & Pricing
    'subscription': 'Subscription',
    'freePlan': 'Free',
    'proPlan': 'Pro',
    'currentPlan': 'Current Plan',
    'freeDesc': 'Get started with basic features',
    'proDesc': 'Unlock the full power of AI scheduling',
    'monthly': 'Monthly',
    'annual': 'Annual',
    'month': 'month',
    'save': 'Save',
    'billedAnnually': 'Billed annually',
    'freeCourses': '2 active courses',
    'freeTopics': '10 topics per course',
    'freeExtractions': '3 AI extractions/month',
    'basicScheduling': 'Basic study scheduling',
    'unlimited': 'Unlimited',
    'coursesLabel': 'courses',
    'topicsPerCourse': 'topics per course',
    'proExtractions': '50 AI extractions/month',
    'aiSmartScheduling': 'AI-powered smart scheduling',
    'spacedRepetition': 'Spaced repetition reviews',
    'dependencyTracking': 'Topic dependency tracking',
    'prioritySupport': 'Priority support',
    'recommended': 'Recommended',
    'downgrade': 'Downgrade',
    'upgradeToPro': 'Upgrade to Pro',
    'active': 'Active',
    'billing': 'billing',
    'renews': 'Renews',
    'manageSubscription': 'Manage Subscription',
    'checkoutStarted': 'Checkout started',
    'completePayment': 'Complete payment in the new tab to activate your subscription.',
    
    // Contact Upgrade
    'contactToUpgrade': 'Contact Us to Upgrade',
    'upgradeMessage': 'To upgrade to the Pro plan, please contact us at the following number:',
    'copyNumber': 'Copy Number',
    'numberCopied': 'Number copied!',
    'copied': 'Copied',
    
    // Course Detail - Files Tab
    'files': 'Files',
    'topics': 'Topics',
    'allocation': 'Allocation',
    'uploadCourseMaterials': 'Upload Course Materials',
    'uploadedFiles': 'Uploaded Files',
    'dropFilesHere': 'Drop PDF files here or click to upload',
    'maxFileSize': 'Maximum file size',
    'uploading': 'Uploading...',
    'extractingText': 'Extracting text...',
    'ready': 'Ready',
    'failed': 'Failed',
    'pending': 'Pending',
    'manualInputNeeded': 'Manual input needed',
    'retry': 'Retry',
    'extractTopics': 'Extract Topics',
    'textExtracted': 'Text extracted!',
    'readyToExtract': 'Ready to extract topics from',
    'extractionFailed': 'Text extraction failed',
    'addManually': 'You can still add topics manually',
    'extractionNotice': 'Extraction notice',
    'fileUploaded': 'File uploaded',
    
    // Course Detail - Topics Tab
    'addContent': 'Add Content',
    'pasteForAI': 'Paste syllabus or topic list here for AI extraction',
    'pasteSyllabusHere': 'Paste syllabus text here...',
    'extractWithAI': 'Extract Topics with AI',
    'extractingWithAI': 'Extracting with AI...',
    'progressOverview': 'Progress Overview',
    'trackCompletion': 'Track topic completion',
    'topicsCompleted': 'topics completed',
    'notStarted': 'Not started',
    'inProgress': 'In progress',
    'done': 'Done',
    'needsReview': 'topic needs your review (low confidence)',
    'topicsCount': 'Topics',
    'reviewTopics': 'Review and edit topics. Set weights (1-5) for difficulty and exam importance.',
    'addManualTopic': 'Add Manual',
    'status': 'Status',
    'title': 'Title',
    'confidence': 'Confidence',
    'source': 'Source',
    'difficulty': 'Difficulty',
    'importance': 'Importance',
    'score': 'Score',
    'actions': 'Actions',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'page': 'p',
    'noSourceContext': 'No source context',
    'noTopicsYet': 'No topics yet. Paste syllabus text above or add manually.',
    'topicLimitReached': 'Topic limit reached',
    'enterTextToExtract': 'Please enter text to extract topics from',
    'loginToExtract': 'Please login to extract topics',
    'topicsExtracted': 'Topics extracted successfully!',
    'someNeedReview': 'Some topics may need review. Check titles and weights.',
    'extractFailed': 'Failed to extract topics',
    'deleteFailed': 'Failed to delete topic',
    'topicDeleted': 'Topic deleted',
    'updateFailed': 'Failed to update topic',
    'statusUpdateFailed': 'Failed to update status',
    
    // Course Detail - Allocation Tab
    'studySchedule': 'Study Schedule',
    'generateScheduleDesc': 'Generate a balanced study plan from now until your exam on',
    'basicSchedule': 'Basic Schedule',
    'aiSmartSchedule': 'AI Smart Schedule',
    'addTopicsFirst': 'Add topics to your course first.',
    'setExamDate': 'Set an exam date to generate a plan.',
    'yourPlan': 'Your Plan',
    'topicsScheduled': 'topics scheduled',
    'scheduleGenerated': 'Study plan generated!',
    'noTopicsFound': 'No topics found. Add topics first.',
    'setExamDateFirst': 'Please set an exam date first.',
    'planError': 'Error generating plan',
    'smartPlanCreated': 'Smart plan created',
    'daysStudySessions': 'days, study sessions!',
    'scheduleWarnings': 'Schedule generated with warnings',
    'topicsCoverage': 'topics were scheduled',
    'aiCreditsExhausted': 'AI credits exhausted. Please add more credits.',
    'rateLimitExceeded': 'Rate limit exceeded. Please try again later.',
    'smartPlanFailed': 'Failed to generate smart plan',
    'planNotCreated': 'Plan was not created because no valid schedule could be generated.',
    'extractionInProgress': 'Topic extraction is already in progress',
    'coursesExcluded': 'Some courses were excluded - no available days before exam',
    'confirmDeletePlan': 'Are you sure you want to delete this study plan? This cannot be undone.',
    'planDeleted': 'Study plan deleted successfully',
    'deletePlan': 'Delete Plan',
    'deletePlanFailed': 'Failed to delete plan',
    'priorityPlanCreated': 'Priority Plan Created',
    'priorityTopicsScheduled': 'highest-priority topics scheduled',
    'priorityModeActive': 'Priority Mode Active',
    'priorityModeDesc': 'Not enough time for all topics. Highest priority topics have been scheduled. Check the Topics tab for remaining topics.',
    'viewRemainingTopics': 'View remaining topics in Topics tab',
    'fallbackSchedulerUsed': 'Fallback scheduler was used',
    
    // Tips
    'filesTip': 'Upload syllabus files (PDF) to extract topics automatically',
    'topicsTip': 'Add topics manually or extract them from uploaded files',
    'allocationTip': 'See how topics are distributed across remaining days until exam',
    
    // Exam
    'exam': 'Exam',
    'daysLeft': 'days',
    'examPassed': 'Exam passed',
    
    // Landing - Navbar
    'login': 'Login',
    'startFree': 'Start Free',
    
    // Landing - Hero
    'heroBadge': 'Smart platform for academic success',
    'heroTitle1': 'Organize your study',
    'heroTitle2': 'Smart & Efficient',
    'heroSubtitle': 'Use AI to automatically organize your study schedule and track your progress until exam day. A complete study experience designed for your success.',
    'startNowFree': 'Start Now Free',
    'browseSchedule': 'Browse Public Schedule',
    'activeStudents': 'Active Students',
    'successRate': 'Success Rate',
    'studyHours': 'Study Hours',
    
    // Landing - How it Works
    'howItWorks': 'How does it',
    'howItWorksHighlight': 'Work?',
    'howItWorksSubtitle': 'Four simple steps to perfectly organize your studies',
    'step1Title': 'Add your courses',
    'step1Desc': 'Enter your courses with exam dates. You can upload your syllabus and let AI extract topics automatically.',
    'step2Title': 'Smart Plan',
    'step2Desc': 'The system distributes topics across remaining days based on importance and difficulty, ensuring complete coverage.',
    'step3Title': 'Track Progress',
    'step3Desc': 'Complete daily tasks and watch your progress in each course. Use Pomodoro technique for optimal focus.',
    'step4Title': 'Achieve Excellence',
    'step4Desc': 'With consistent tracking and smart organization, you\'ll be ready for exams with confidence and calm.',
    
    // Landing - Features
    'featuresTitle': 'Everything you need',
    'featuresTitleHighlight': 'in one place',
    'featuresSubtitle': 'Integrated tools designed specifically to help you excel',
    'feature1Title': 'Comprehensive Dashboard',
    'feature1Desc': 'Track your daily achievements and study statistics in one place',
    'feature2Title': 'Smart Schedules',
    'feature2Desc': 'Customized schedules that fit your time and courses',
    'feature3Title': 'Pomodoro Timer',
    'feature3Desc': 'Built-in Pomodoro technique for effective and focused study sessions',
    'feature4Title': 'Smart Extraction',
    'feature4Desc': 'AI automatically extracts topics from your files',
    'feature5Title': 'Progress Tracking',
    'feature5Desc': 'Visual charts showing your progress in each course',
    'feature6Title': 'Course Management',
    'feature6Desc': 'Organize courses, set priorities, and track each one precisely',
    
    // Landing - Footer
    'publicSchedule': 'Public Schedule',
    'allRightsReserved': 'All rights reserved.',
    
    // Pomodoro
    'pomodoroTimer': 'Pomodoro Timer',
    'focusTime': 'Focus Time',
    'shortBreak': 'Short Break',
    'longBreak': 'Long Break',
    'start': 'Start',
    'pause': 'Pause',
    'reset': 'Reset',
    'sessionsCompleted': 'Sessions Completed',
    'sessionRecorded': 'Focus session recorded!',
    'stayFocused': 'Stay focused! 💪',
    'takeBreak': 'Enjoy your break ☕',
    'greatWork': 'Great work! 🎉',
    
    // Dashboard
    'goodMorning': 'Good morning',
    'goodAfternoon': 'Good afternoon',
    'goodEvening': 'Good evening',
    'letsStudy': "Let's study! 📚",
    'newCourse': 'New Course',
    'hoursToday': 'Hours Today',
    'completedItems': 'Completed',
    'remainingItems': 'Remaining',
    'progress': 'Progress',
    'todayPlan': "Today's Plan",
    'createPlan': 'Create Plan',
    'dailyProgress': 'Daily Progress',
    'generalStudy': 'General Study',
    'viewFullPlan': 'View Full Plan',
    'noPlanYet': 'No plan yet',
    'noPlanDesc': 'Create a custom study plan based on your courses and exam dates',
    'upcomingExams': 'Upcoming Exams',
    'ended': 'Ended',
    'hours': 'h',
    
    // Dashboard - Welcome (New Users)
    'welcomeTitle': 'Welcome to StudyBudy',
    'welcomeSubtitle': 'Start your study journey by adding your first course. We\'ll help you organize your time and achieve your goals.',
    'howToStart': 'How to start?',
    'addFirstCourseStep': 'Add your first course',
    'addFirstCourseDesc': 'Enter course name and exam date, you can upload syllabus if available',
    'addTopicsStep': 'Add topics',
    'addTopicsDesc': 'Add topics manually or let AI extract them from your file',
    'getPlanStep': 'Get your plan',
    'getPlanDesc': 'We\'ll generate a smart daily schedule distributing topics based on remaining time',
    'addFirstCourse': 'Add your first course',
    
    // TodayOverview
    'today': 'Today',
    'completed': 'completed',
    'noTasksToday': 'No tasks scheduled for today',
    'enjoyDay': 'Enjoy your day! 🎉',
    
    // Subjects
    'os': 'Operating Systems',
    'circuits': 'Circuits',
    'automata': 'Automata',
    
    // Days
    'sunday': 'Sunday',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    
    // Study Tips
    'studyTips': 'Study Tips',
    'tipActiveRecallTitle': 'Active Recall',
    'tipActiveRecallDesc': 'Test yourself frequently instead of just re-reading. Try to recall information from memory before checking your notes.',
    'tipPomodoroTitle': 'Pomodoro Technique',
    'tipPomodoroDesc': 'Study in 25-minute focused blocks with 5-minute breaks. After 4 blocks, take a longer 15-30 minute break.',
    'tipPrioritizeTitle': 'Prioritize Difficult Topics',
    'tipPrioritizeDesc': 'Tackle challenging subjects when your energy is highest, usually in the morning or after a break.',
    'tipHydratedTitle': 'Stay Hydrated',
    'tipHydratedDesc': 'Drink water regularly. Dehydration can significantly impair concentration and cognitive function.',
    'tipSpacedRepTitle': 'Spaced Repetition',
    'tipSpacedRepDesc': 'Review material at increasing intervals. This helps move information from short-term to long-term memory.',

    // AddTopicDialog
    'enterTopicTitleFirst': 'Please enter topic title first',
    'topicAnalyzedWithAI': 'Topic analyzed with AI',
    'topicAnalysisFailed': 'Topic analysis failed: ',
    'unknownError': 'Unknown error',
    'enterTopicTitle': 'Please enter topic title',
    'topicAddedSuccess': 'Topic added successfully',
    'topicAddFailed': 'Failed to add topic: ',
    'addNewTopic': 'Add New Topic',
    'addNewTopicDesc': 'Add a new topic manually. You can set difficulty and importance or let AI suggest them.',
    'topicTitleLabel': 'Topic Title *',
    'topicTitlePlaceholder': 'e.g. Differential Equations',
    'notesOptional': 'Notes (Optional)',
    'notesPlaceholder': 'Any additional notes about the topic...',
    'difficultyLabel': 'Difficulty: ',
    'difficultyHelp': '1 = Easy, 5 = Hard',
    'importanceLabel': 'Exam Importance: ',
    'importanceHelp': '1 = Low, 5 = High',
    'analyzeWithAILabel': 'Analyze with AI to suggest weights',
    'calculatedScore': 'Calculated Score: ',
    'addTopicButton': 'Add Topic',
    'adding': 'Adding...',
    'cancel': 'Cancel',

    // Edit/Delete Course
    'editCourse': 'Edit Course',
    'editCourseDesc': 'Update course details and exam date',
    'examDate': 'Exam Date',
    'selectDate': 'Select date',
    'courseUpdated': 'Course updated successfully',
    'courseNameRequired': 'Course name is required',
    'deleteCourse': 'Delete Course',
    'deleteCourseConfirm': 'Are you sure you want to delete',
    'deleteWarningTopics': 'This will also delete all topics and related data.',
    'actionCannotBeUndone': 'This action cannot be undone.',
    'courseDeleted': 'Course deleted successfully',

    // CreateCourseDialog
    'courseCreatedSuccess': 'Course created successfully!',
    'addCourse': 'Add Course',
    'addNewCourse': 'Add New Course',
    'addNewCourseDesc': 'Add a course or exam you are preparing for',
    'courseNameLabel': 'Course Name',
    'courseNamePlaceholder': 'e.g. Advanced Mathematics',
    'examDateOptional': 'Exam Date (Optional)',
    'examDateHelp': 'We will use this date to distribute topics over remaining days',
    'remainingLimit': 'You have',
    'course': 'course',
    'courses_plural': 'courses',
    'inCurrentPlan': 'remaining in your current plan',
    'creating': 'Creating...',
    'createCourseButton': 'Create Course',

    // UpgradeCard
    'benefits_course_limit_1': 'Add unlimited courses',
    'benefits_course_limit_2': 'Smart topic extraction from your files',
    'benefits_course_limit_3': 'Advanced progress analytics',
    'benefits_ai_limit_1': 'Unlimited smart extraction',
    'benefits_ai_limit_2': 'Automatic topic prioritization',
    'benefits_ai_limit_3': 'Faster study plan generation',
    'benefits_general_1': 'Unlimited courses',
    'benefits_general_2': 'Smart topic extraction',
    'benefits_general_3': 'Advanced analytics and stats',
    'title_course_limit': 'Add More Courses',
    'title_ai_limit': 'Unlock AI Power',
    'title_general': 'Upgrade Your Study Experience',
    'subtitle_course_limit': 'You reached the maximum number of courses. Upgrade now to organize all your courses in one place.',
    'subtitle_ai_limit': 'You exhausted your smart extractions. Upgrade for unlimited topic extractions.',
    'subtitle_general': 'Get powerful tools to organize your study and achieve your academic goals.',
    'upgradePlan': 'Upgrade Plan',
    'youAreInTrial': 'You are in trial period',
    'planNamePrefix': 'Plan',
    'upgradeNow': 'Upgrade Now',
    'cancelAnytime': 'Cancel anytime • 7-day money-back guarantee',

    // SoftLimitWarning
    'limit_warning_courses': 'Used {current} of {limit} courses',
    'limit_critical_courses': 'One course remaining!',
    'limit_reached_courses': 'Max courses reached',
    'limit_warning_topics': '{current}/{limit} topics',
    'limit_critical_topics': 'Few topics remaining!',
    'limit_reached_topics': 'Max topics reached',
    'limit_warning_ai': '{current}/{limit} extractions',
    'limit_critical_ai': 'One extraction remaining!',
    'limit_reached_ai': 'Extractions exhausted',
    'upgrade': 'Upgrade',

    // PlanWarningBanner
    'severeTimeConstraint': 'Severe Time Constraint',
    'timeConstraintWarning': 'Time Constraint Warning',
    'youNeedHours': 'You need {required} hours but only have {available} hours available.',
    'butHaveHours': '',
    'coverageRatio': 'Coverage ratio: {percent}% of ideal study time.',
    'ofIdealStudyTime': '',
    'studyHoursCompressed': ' Study hours have been compressed.',
    'considerSuggestions': 'Consider: Extending daily study hours, adding more study days, or postponing the exam if possible.',

    // UsageIndicator
    'freeTrial': 'Free Trial',
    'nearLimit': 'Near Limit',
    'usage': 'Usage',

    // Courses List
    'noCoursesTitle': 'No courses yet',
    'noCoursesDesc': 'Add your first course to start organizing your studies. You can upload a syllabus or add topics manually.',
    'todayExclamation': 'Today!',
    'noExamDate': 'No exam date set',
    'completedTopicsCount': '{completed} of {total} topics completed',

    // Exam Countdown Card
    'nextExam': 'NEXT',
    'urgent': 'URGENT',
    'examCompleted': 'Exam completed',
    'daysShort': 'Days',
    'hoursShort': 'Hrs',
    'minutesShort': 'Min',
    'secondsShort': 'Sec',
    'topicsNeededPerDay': '~{count} topics/day needed',
    'percentComplete': '{percent}% complete',

    // Plan Page
    'studyPlan': 'Study Plan',
    'customScheduleDesc': 'Your personalized daily study schedule',
    'planCreated': 'Plan created!',
    'planCreatedDesc': 'Created {days} days with {items} study topics',
    'planFailed': 'Failed to create plan',
    'tryAgain': 'Try again',
    'weekReplanned': 'Week replanned!',
    'missedItemsDistributed': 'Distributed {count} missed topics to upcoming days',
    'replanFailed': 'Failed to replan',
    'recreatePlan': 'Recreate Plan',
    'daysUntilExam': 'Days until exam',
    'dailyHours': 'Daily hours',
    'remainingTopics': 'Remaining topics',
    'restDay': 'Rest Day',
    'enjoyRestDay': 'Enjoy your rest day! 🌴',
    'noScheduledTopics': 'No scheduled topics',
    'tomorrow': 'Tomorrow',
    'tasks': 'tasks',

    // Dashboard extras
    'studyTipsTitle': 'Study Tips & Techniques',
    'tipsCount': '{count} tips',
    'detailedSchedule': 'Detailed Schedule ({days} days)',
    'moreDays': '+{count} more days...',
    'viewAllExams': 'View all {count} exams',

    // Calendar Integration
    'calendarSync': 'Calendar Sync',
    'connectGoogleCalendar': 'Connect Google Calendar',
    'disconnectCalendar': 'Disconnect Calendar',
    'calendarConnected': 'Calendar Connected',
    'syncNow': 'Sync Now',
    'syncing': 'Syncing...',
    'syncSuccess': 'Synced successfully!',
    'autoSync': 'Auto-sync',
    'autoSyncDesc': 'Automatically sync your plan to Google Calendar',
    'calendarNotConnected': 'Calendar not connected',
    'connectCalendarDesc': 'Connect Google Calendar to add your study plan automatically',
    'syncToCalendar': 'Sync to Calendar',
    'eventsCreated': 'Created {count} events in your calendar',

    // Account Management
    'dangerZoneDesc': 'Irreversible actions',
    'exportData': 'Export your data',
    'exportDataDesc': 'Download all your data as JSON',
    'export': 'Export',
    'exportSuccess': 'Data exported',
    'exportSuccessDesc': 'Your data file has been downloaded successfully',
    'exportFailed': 'Failed to export data',
    'deleteAccount': 'Delete account',
    'deleteAccountDesc': 'Permanently delete your account and all data',
    'delete': 'Delete',
    'confirmDeleteAccount': 'Confirm account deletion',
    'deleteAccountWarning': 'This action cannot be undone. All your data including courses, topics, plans, and files will be permanently deleted.',
    'enterPasswordToConfirm': 'Enter password to confirm',
    'permanentlyDelete': 'Permanently delete',
    'incorrectPassword': 'Incorrect password',
    'accountDeleted': 'Account deleted',
    'accountDeletedDesc': 'Your account and all data have been deleted successfully',
    'deleteAccountFailed': 'Failed to delete account',

    // Legal Pages
    'termsOfService': 'Terms of Service',
    'privacyPolicy': 'Privacy Policy',

    // Password Reset & File Management
    'resetPasswordTitle': 'Reset Password',
    'resetPasswordDesc': 'Send a password reset link to your email',
    'passwordResetSent': 'Password Reset Email Sent',
    'checkEmailForReset': 'Check your email for the password reset link',
    'confirmDeleteFile': 'Confirm Delete File',
    'deleteFileWarning': 'Are you sure you want to delete this file?',
    'fileDeleted': 'File deleted successfully',
    'deleteFileFailed': 'Failed to delete file',
    'topicQuotaReached': 'Topic limit reached',
    'upgradeForMoreTopics': 'Upgrade to Pro for unlimited topics',
    
    // Upload race condition
    'waitForUploadsToFinish': 'Please wait for all files to finish uploading before extracting topics',
    
    // Triage mode warnings
    'triageModeActive': 'Triage Mode Active',
    'triageModeDesc': 'Not enough time for all topics. Only highest-priority topics were scheduled.',
    'viewAllTopics': 'View All Topics',
    'topicsNotScheduled': 'topics could not be scheduled',
    
    // Schedule errors
    'examDateConflict': 'Exam Date Conflict',
    'noAvailableDays': 'No available days before exam',
    'checkExamDate': 'Check exam dates and days off settings',
    
    // Admin
    'proOverride': 'Pro (Override)',
    'trialActive': 'Trial Active',
    'trialDaysLeft': 'days left',

    // Onboarding hints
    'hintStep': 'Step',
    'hintGetStarted': 'Get Started',
    'hintNoCoursesTitle': 'Start Your Study Journey',
    'hintNoCoursesDesc': 'Add your first course to organize your studies. Click the button above to add a course.',
    'hintAddTopicsTitle': 'Add Your Topics',
    'hintAddTopicsDesc': 'After creating a course, add topics manually or extract them from PDF files.',
    'hintGeneratePlanTitle': 'Generate Your Plan',
    'hintGeneratePlanDesc': 'Once you have topics, go to the "Plan" page to create a smart study schedule.',
    'hintNavigateToCoursesBtn': 'Go to Courses',
    'hintNavigateToPlanBtn': 'Go to Plan',
    'nextStep': 'Next Step',
    'currentStep': 'Current Step',
    'completedStep': 'Completed',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('zen-study-language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('zen-study-language', lang);
    // Update document direction
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function LanguageToggle() {
  const { language, setLanguage } = useLanguage();

  return (
    <button
      onClick={() => setLanguage(language === 'ar' ? 'en' : 'ar')}
      className="px-3 py-1.5 rounded-lg bg-secondary/50 hover:bg-secondary text-sm font-medium transition-colors"
    >
      {language === 'ar' ? 'EN' : 'عربي'}
    </button>
  );
}